@host =  http://localhost:3000
@aggregatorURL = {{host}}/aggregator
###
GET {{aggregatorURL}}


###Get service List ###
POST {{aggregatorURL}}/serviceList
Content-Type: application/json

{
    "schemeName":"test",
    "services":[1,2,3]
}


###Get service List ###
POST {{aggregatorURL}}/serviceList2
Content-Type: application/json

{
    
    "services":[1,2,3]
}