@host =  http://localhost:3000

POST {{host}}/scheme/add_scheme
Content-Type: application/json

{
    "schemeFor":"aggregator2",
    "scheme": ["ser_id","ar_name","en_name","amount","service_charge","requests"],
    "schemeType":"with_scheme",
    "sub_keys":["amount.credit", "amount.scale","amount.calculate_fee"]
}

###
POST {{host}}/scheme/add_scheme
Content-Type: application/json

{
    "schemeFor":"general",
    "scheme": ["ser_id","provider_id","description","ar_name", "en_name","description","sp_config","amount","service_charge","requests","main_biller","receipt","sector"],
    "schemeType":"with_scheme"
}



###
POST http://10.22.1.186:3003/billers?cache=false
Content-Type: application/json

{
    "id" : "871",
    "en_name":"orange control",
    "ar_name":"باقة نظامك الشهري",
    "code" : "1",
    "status" : "1",
    "main_biller_id" : "14",
    "service_provider_id" : "2"
}
