@host =  http://localhost:3000


###
GET http://localhost:6001/seed

###
GET {{host}}/getEnv

###
GET {{host}}/service_Repo
Content-Type: application/json
###
GET {{host}}/

###
GET {{host}}/test/func22 

###
GET {{host}}/test

###
POST {{host}}/asd
Content-Type: application/json


  {
    "ser_id": 100001211100,
    "provider_id": 10,
    "en_name": "xXXX2xXX",
    "ar_name": "aasd222adasd",
    "sp_config": {},
    "data_fields": {
        "mobile": {
            "ar_label": "رقم الموبايل",
            "en_label": "bill ID",
            "field_name": "mobile",
            "max_len": "11",
            "min_len": "11",
            "visible": true,
            "required": true,
            "input_type": "N",
            "confirmed": true
        },
        "bills_count": {
            "ar_label": "عدد الأقساط",
            "en_label": "bills count",
            "field_name": "bills_count",
            "input_type": "S"
        },
        "total_payable_amount": {
            "ar_label": "القيمة الكلية",
            "en_label": " Total Payable Amount",
            "field_name": "total_payable_amount",
            "input_type": "S"
        }
    },
    "amount": {
        "ar_label": "القيمة",
        "en_label": "amount",
        "field_name": "amount",
        "valueType": "range",
        "range_min": 5,
        "range_max": 10000,
        "is_user_entered": true,
        "calculate_fee": true,
        "replace": [
            "range_max",
            "total_payable_amount"
        ],
        "credit": true
    },
    "service_charge": {
        "ar_label": "تكلفة الخدمة",
        "en_label": "service charge",
        "field_name": "service_charge",
        "slides": [
            {
                "scValueType": "F",
                "fromValue": 1,
                "toValue": 1000000000,
                "scValue": 10
            }
        ]
    },
    "requests": [
        {
            "name": "valu_inq",
            "order": 1,
            "request_type": "I",
            "inputs": [
                "mobile"
            ],
            "outputs": [
                "bills_count",
                "total_payable_amount"
            ]
        },
        {
            "name": "valu_pay",
            "order": 2,
            "request_type": "P",
            "inputs": [
                "mobile",
                "amount",
                "service_charge"
            ],
            "outputs": []
        }
    ],
    "main_biller": "معاملات مالية و بنوك",
    "receipt": {
        "template_id": 7,
        "optional": false
    }
  }


###
POST {{host}}/add_new_service
Content-Type: application/json

{
    "provider_id": 5,
    "ar_name": "test22",
    "en_name":"asdasd",
    "description": "مصر الخير تبرعات",
    "sp_config":{},
    "amount": {
        "ar_label": "القيمة",
        "en_label": "amount",
        "field_name": "amount",
        "valueType": "range",
        "range_min": 10,
        "range_max": 1000,
        "is_user_entered": true,
        "calculate_fee": false,
        "credit": true
    },
    "service_charge": {
        "ar_label": "تكلفة الخدمة",
        "en_label": "service charge",
        "field_name": "service_charge",
        "slides": [
            {
                "fromValue": 0,
                "toValue": 1000,
                "scValue": 0,
                "scValueType": "P"
            }
        ]
    },
    "requests": [
        {
            "name": "damen_pay",
            "order": 1,
            "request_type": "P",
            "inputs": [
                "amount",
                "mobile"
            ],
            "outputs": []
        }
    ],
    "main_biller": "مصر الخير",
    "receipt": {
        "template_id": 1,
        "optional": false
    },
    sector:"تجربة"
    
}

###
POST {{host}}/update_service/890
Content-Type: application/json

{
    "provider_id": 5,
    "ar_name": "احمد عبدالله",
    "en_name":"ahmed Abdullah",
    "description": "مصر الخير تبرعات",
    "sp_config":{},
    "amount": {
        "ar_label": "القيمة",
        "en_label": "amount",
        "field_name": "amount",
        "valueType": "range",
        "range_min": 10,
        "range_max": 1000,
        "is_user_entered": true,
        "calculate_fee": false,
        "credit": true
    },
    "service_charge": {
        "ar_label": "تكلفة الخدمة",
        "en_label": "service charge",
        "field_name": "service_charge",
        "slides": [
            {
                "fromValue": 0,
                "toValue": 1000,
                "scValue": 0,
                "scValueType": "P"
            }
        ]
    },
    "requests": [
        {
            "name": "damen_pay",
            "order": 1,
            "request_type": "P",
            "inputs": [
                "amount",
                "mobile"
            ],
            "outputs": []
        }
    ],
    "main_biller": "مصر الخير",
    "receipt": {
        "template_id": 1,
        "optional": false
    },
    "sector":"تجربة"
}


###
GET {{host}}/service/1000
























###
GET http://10.22.1.186:3003/billers
Content-Type: "application/json"


######
POST http://10.22.1.186:3002/report/schedulers/run
Content-Type: application/json

{
  "date":"2022-01-20",
  "reportConfigId":"61e8179a25c4510a3afde3d4",
  "forceRun":1,
    "mailerReceivers":{
      "to":["a.soliman@egyptsmartcards.com"]
  }
}
